# Welcome to serverless. Read the docs
# https://serverless.com/framework/docs/

# Serverless.yml is the configuration the CLI
# uses to deploy your code to your provider of choice

# The `service` block is the name of the service
service: serverless-auth

plugins:
  - serverless-offline

# Configuration variables
custom:
  secrets: ${file(secrets.json)}

# The `provider` block defines where your service will be deployed
provider:
  name: aws
  runtime: nodejs8.10
  profile: personal
  region: us-west-2
  environment:
    JWT_SECRET: ${self:custom.secrets.jwtSecret}

# The `functions` block defines what code to deploy
functions:
  login:
    handler: functions/login.handler
    events:
      - http:
          path: sessions
          method: post
          cors: true
  authorize:
    handler: functions/authorize.handler
  getPosts:
    handler: functions/getPosts.handler
    events:
      - http:
          path: posts
          method: get
          cors: true
          # authorizer: authorize # Posts are public
  getPrivate:
    handler: functions/getPrivate.handler
    events:
      - http:
          path: private
          method: get
          cors: true
          authorizer: authorize # Private are protected
